jwt:
  secret: 2b8629ac53be1a14aea0fd005d89b881435bb6f03be963b26868f8403af6e5bf
  expirationMs: 604800000
server:
  port: 9089
spring:
  application:
    name: freelance-clone
  datasource:
    url: jdbc:mysql://localhost:3306/freelancer-clone?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: furkan2023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
grpc:
  server:
    port: 9090
    inProcessName: test
