// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/TcDogrula.proto

// Protobuf Java Version: 3.25.1
package com.kurtlar.konseyi.freelancerclone.grpc;

public interface TcDogrulaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool TCKimlikNoDogrulaResult = 1;</code>
   * @return The tCKimlikNoDogrulaResult.
   */
  boolean getTCKimlikNoDogrulaResult();
}
