// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/TcDogrula.proto

// Protobuf Java Version: 3.25.1
package com.kurtlar.konseyi.freelancerclone.grpc;

public final class TcDogrula  {
  private TcDogrula() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/resources/TcDogrula.proto\022(co" +
      "m.kurtlar.konseyi.freelancerclone.grpc\"T" +
      "\n\020TcDogrulaRequest\022\022\n\nTCKimlikNo\030\001 \001(\t\022\n" +
      "\n\002Ad\030\002 \001(\t\022\r\n\005Soyad\030\003 \001(\t\022\021\n\tDogumYili\030\004" +
      " \001(\005\"4\n\021TcDogrulaResponse\022\037\n\027TCKimlikNoD" +
      "ogrulaResult\030\001 \001(\0102\244\001\n\020TcDogrulaService\022" +
      "\217\001\n\024getTCKimlikNoDogrula\022:.com.kurtlar.k" +
      "onseyi.freelancerclone.grpc.TcDogrulaReq" +
      "uest\032;.com.kurtlar.konseyi.freelancerclo" +
      "ne.grpc.TcDogrulaResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaRequest_descriptor,
        new java.lang.String[] { "TCKimlikNo", "Ad", "Soyad", "DogumYili", });
    internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_descriptor,
        new java.lang.String[] { "TCKimlikNoDogrulaResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
