// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/TcDogrula.proto

// Protobuf Java Version: 3.25.1
package com.kurtlar.konseyi.freelancerclone.grpc;

public interface TcDogrulaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string TCKimlikNo = 1;</code>
   * @return The tCKimlikNo.
   */
  java.lang.String getTCKimlikNo();
  /**
   * <code>string TCKimlikNo = 1;</code>
   * @return The bytes for tCKimlikNo.
   */
  com.google.protobuf.ByteString
      getTCKimlikNoBytes();

  /**
   * <code>string Ad = 2;</code>
   * @return The ad.
   */
  java.lang.String getAd();
  /**
   * <code>string Ad = 2;</code>
   * @return The bytes for ad.
   */
  com.google.protobuf.ByteString
      getAdBytes();

  /**
   * <code>string Soyad = 3;</code>
   * @return The soyad.
   */
  java.lang.String getSoyad();
  /**
   * <code>string Soyad = 3;</code>
   * @return The bytes for soyad.
   */
  com.google.protobuf.ByteString
      getSoyadBytes();

  /**
   * <code>int32 DogumYili = 4;</code>
   * @return The dogumYili.
   */
  int getDogumYili();
}
