// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/TcDogrula.proto

// Protobuf Java Version: 3.25.1
package com.kurtlar.konseyi.freelancerclone.grpc;

/**
 * Protobuf type {@code com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse}
 */
public final class TcDogrulaResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse)
    TcDogrulaResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TcDogrulaResponse.newBuilder() to construct.
  private TcDogrulaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TcDogrulaResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TcDogrulaResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kurtlar.konseyi.freelancerclone.grpc.TcDogrula.internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kurtlar.konseyi.freelancerclone.grpc.TcDogrula.internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse.class, com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse.Builder.class);
  }

  public static final int TCKIMLIKNODOGRULARESULT_FIELD_NUMBER = 1;
  private boolean tCKimlikNoDogrulaResult_ = false;
  /**
   * <code>bool TCKimlikNoDogrulaResult = 1;</code>
   * @return The tCKimlikNoDogrulaResult.
   */
  @java.lang.Override
  public boolean getTCKimlikNoDogrulaResult() {
    return tCKimlikNoDogrulaResult_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tCKimlikNoDogrulaResult_ != false) {
      output.writeBool(1, tCKimlikNoDogrulaResult_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tCKimlikNoDogrulaResult_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, tCKimlikNoDogrulaResult_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse)) {
      return super.equals(obj);
    }
    com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse other = (com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse) obj;

    if (getTCKimlikNoDogrulaResult()
        != other.getTCKimlikNoDogrulaResult()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TCKIMLIKNODOGRULARESULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTCKimlikNoDogrulaResult());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse)
      com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kurtlar.konseyi.freelancerclone.grpc.TcDogrula.internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kurtlar.konseyi.freelancerclone.grpc.TcDogrula.internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse.class, com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse.Builder.class);
    }

    // Construct using com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tCKimlikNoDogrulaResult_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kurtlar.konseyi.freelancerclone.grpc.TcDogrula.internal_static_com_kurtlar_konseyi_freelancerclone_grpc_TcDogrulaResponse_descriptor;
    }

    @java.lang.Override
    public com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse getDefaultInstanceForType() {
      return com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse build() {
      com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse buildPartial() {
      com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse result = new com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tCKimlikNoDogrulaResult_ = tCKimlikNoDogrulaResult_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse) {
        return mergeFrom((com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse other) {
      if (other == com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse.getDefaultInstance()) return this;
      if (other.getTCKimlikNoDogrulaResult() != false) {
        setTCKimlikNoDogrulaResult(other.getTCKimlikNoDogrulaResult());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              tCKimlikNoDogrulaResult_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean tCKimlikNoDogrulaResult_ ;
    /**
     * <code>bool TCKimlikNoDogrulaResult = 1;</code>
     * @return The tCKimlikNoDogrulaResult.
     */
    @java.lang.Override
    public boolean getTCKimlikNoDogrulaResult() {
      return tCKimlikNoDogrulaResult_;
    }
    /**
     * <code>bool TCKimlikNoDogrulaResult = 1;</code>
     * @param value The tCKimlikNoDogrulaResult to set.
     * @return This builder for chaining.
     */
    public Builder setTCKimlikNoDogrulaResult(boolean value) {

      tCKimlikNoDogrulaResult_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool TCKimlikNoDogrulaResult = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTCKimlikNoDogrulaResult() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tCKimlikNoDogrulaResult_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse)
  }

  // @@protoc_insertion_point(class_scope:com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse)
  private static final com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse();
  }

  public static com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TcDogrulaResponse>
      PARSER = new com.google.protobuf.AbstractParser<TcDogrulaResponse>() {
    @java.lang.Override
    public TcDogrulaResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TcDogrulaResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TcDogrulaResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kurtlar.konseyi.freelancerclone.grpc.TcDogrulaResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

